name: compose-now

services:
  gateway:
    build:
      context: .
      target: dev
    image: gateway:dev
    restart: always
    networks:
      - radx
    env_file:
      - ../.env
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: ${DOTNET_USE_POLLING_FILE_WATCHER}
      DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER: ${DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER}
      ASPNETCORE_ENVIRONMENT: ${APP_MODE}
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: "true"
    ports:
      - "${ASPNETCORE_PORT}:5001"
    volumes:
      - ../app:/app
      - ../vst_builds:/plugins:ro
      - ../logs:/logs
      - /app/obj
      - /app/bin

  # worker:
  #   build:
  #     context: .
  #     target: dev
  #   image: worker:dev
  #   restart: on-failure
  #   networks:
  #     - radx
  #   env_file:
  #     - ../.env
  #   environment:
  #     DOTNET_USE_POLLING_FILE_WATCHER: ${DOTNET_USE_POLLING_FILE_WATCHER}
  #     DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER: ${DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER}
  #     ASPNETCORE_ENVIRONMENT: ${APP_MODE}
        # DOTNET_WATCH_RESTART_ON_RUDE_EDIT: "true"
  #   volumes:
  #     - ../worker:/app
  #     - ../vst_builds:/plugins:ro
  #     - ../logs:/logs
  #     - /app/obj
  #     - /app/bin

  redis:
    restart: always
    image: redis:8.6.1
    volumes:
      - ../redis:/data
    networks:
      - radx
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  radx:
    name: radx
    external: true